name: QA Branch Protection

on:
  pull_request_target:
    types:
      - opened
    branches:
      - QA

jobs:
  check-branch-qa:
    if: github.run_number != 1
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 20 seconds
        run: sleep 20s
        shell: bash
      - name: Check branch
        run: |
          if [[ ${GITHUB_HEAD_REF} != Development ]] && ! [[ ${GITHUB_HEAD_REF} =~ ^hotfix/ ]];
          then
            echo "Error: Pull request must come from the Development branch"
            exit 1
          fi
